ignore:
  - "tests/*"
  - "grands/*"
  - "q1k/analyses/*"
  - "q1k/init/*"
  - "q1k/notebooks/*"
  - "q1k/pylossless/*"
  - "q1k/sync_loss/*"
  - "q1k/*/x*.py"
  - "q1k/*/xtest_*.py"
  - "q1k/autorej/pipeline.py"
  - "q1k/q1k_manager.py"
  - "q1k/xq1k_manager.py"
  - "q1k_dashboard/*"
